import { createContext } from "react";

interface LawContextType {
  isPublic1Open: boolean;
  setIsPublic1Open: (value:boolean)=>void;
  isPublic2Open: boolean;
  setIsPublic2Open: (value:boolean)=>void;
  isPublic3Open: boolean;
  setIsPublic3Open: (value:boolean)=>void;
  isPublic4Open: boolean;
  setIsPublic4Open: (value:boolean)=>void;
  isCriminal1Open: boolean;
  setIsCriminal1Open: (value:boolean)=>void;
  isCriminal2Open: boolean;
  setIsCriminal2Open: (value:boolean)=>void;
  isCriminal3Open: boolean;
  setIsCriminal3Open: (value:boolean)=>void;
  isCriminal4Open: boolean;
  setIsCriminal4Open: (value:boolean)=>void;
  isCivil1Open: boolean;
  setIsCivil1Open: (value:boolean)=>void;
  isCivil2Open: boolean;
  setIsCivil2Open: (value:boolean)=>void;
  isCivil3Open: boolean;
  setIsCivil3Open: (value:boolean)=>void;
  isCivil4Open: boolean;
  setIsCivil4Open: (value:boolean)=>void;
  isCommercial1Open: boolean;
  setIsCommercial1Open: (value:boolean)=>void;
  isCommercial2Open: boolean;
  setIsCommercial2Open: (value:boolean)=>void;
  isCommercial3Open: boolean;
  setIsCommercial3Open: (value:boolean)=>void;
  isCommercial4Open: boolean;
  setIsCommercial4Open: (value:boolean)=>void;
  isAdministrative1Open: boolean;
  setIsAdministrative1Open: (value:boolean)=>void;
  isAdministrative2Open: boolean;
  setIsAdministrative2Open: (value:boolean)=>void;
  isAdministrative3Open: boolean;
  setIsAdministrative3Open: (value:boolean)=>void;
  isAdministrative4Open: boolean;
  setIsAdministrative4Open: (value:boolean)=>void;
  isProcedural1Open: boolean;
  setIsProcedural1Open: (value:boolean)=>void;
  isProcedural2Open: boolean;
  setIsProcedural2Open: (value:boolean)=>void;
  isProcedural3Open: boolean;
  setIsProcedural3Open: (value:boolean)=>void;
  isProcedural4Open: boolean;
  setIsProcedural4Open: (value:boolean)=>void;
};

export const LawContext = createContext<LawContextType|null>(null);